export const LOAD_HOTELS = 'LOAD_HOTELS';
export const LOAD_HOTELS_SUCCESS = 'LOAD_HOTELS_SUCCESS';
export const LOAD_HOTELS_FAIL = 'LOAD_HOTELS_FAIL';


export const LOAD_FAQ = 'LOAD_FAQ';
export const LOAD_FAQ_SUCCESS = 'LOAD_FAQ_SUCCESS';
export const LOAD_FAQ_FAIL = 'LOAD_FAQ_FAIL';



export const LOAD_HOTELS_DETAIL = 'LOAD_HOTELS_DETAIL';
export const LOAD_HOTELS_DETAIL_SUCCESS = 'LOAD_HOTELS_DETAIL_SUCCESS';
export const LOAD_HOTELS_DETAIL_FAIL = 'LOAD_HOTELS_DETAIL_FAIL';



export const SAVE_BOOKING_STATE = 'SAVE_BOOKING_STATE';
export const LOAD_BOOKING_STATE = 'LOAD_BOOKING_STATE';



export const LOAD_DESTINATIONS = 'LOAD_DESTINATIONS';
export const LOAD_DESTINATIONS_SUCCESS = 'LOAD_DESTINATIONS_SUCCESS';
export const LOAD_DESTINATIONS_FAIL = 'LOAD_DESTINATIONS_FAIL';

export const DEST_DETAILS = 'DEST_DETAILS';
export const DEST_DETAILS_SUCCESS = 'DEST_DETAILS_SUCCESS';
export const DEST_DETAILS_FAIL = 'DEST_DETAILS_FAIL';


export const LOAD_TOUR = 'LOAD_TOUR';
export const LOAD_TOUR_SUCCESS = 'LOAD_TOUR_SUCCESS';
export const LOAD_TOUR_FAIL = 'LOAD_TOUR_FAIL';


export const LOAD_CARS = 'LOAD_CARS';
export const LOAD_CARS_SUCCESS = 'LOAD_CARS_SUCCESS';
export const LOAD_CARS_FAIL = 'LOAD_CARS_FAIL';


export const TOUR_DETAILS = 'TOUR_DETAILS';
export const TOUR_DETAILS_SUCCESS = 'TOUR_DETAILS_SUCCESS';
export const TOUR_DETAILS_FAIL = 'TOUR_DETAILS_FAIL';



export const BLOG_LIST = 'BLOG_LIST';
export const BLOG_LIST_SUCCESS = 'BLOG_LIST_SUCCESS';
export const BLOG_LIST_FAIL = 'BLOG_LIST_FAIL';


export const BLOG_READ = 'BLOG_READ';
export const BLOG_READ_SUCCESS = 'BLOG_READ_SUCCESS';
export const BLOG_READ_FAIL = 'BLOG_READ_FAIL';


export const ABOUT_PAGE = 'ABOUT_PAGE';
export const ABOUT_PAGE_SUCCESS = 'ABOUT_PAGE_SUCCESS';
export const ABOUT_PAGE_FAIL = 'ABOUT_PAGE_FAIL';



export const IMPORANT_PAGE = 'IMPORANT_PAGE';
export const IMPORANT_PAGE_SUCCESS = 'IMPORANT_PAGE_SUCCESS';
export const IMPORANT_PAGE_FAIL = 'IMPORANT_PAGE_FAIL';



export const PRIVACY_PAGE = 'PRIVACY_PAGE';
export const PRIVACY_PAGE_SUCCESS = 'PRIVACY_PAGE_SUCCESS';
export const PRIVACY_PAGE_FAIL = 'PRIVACY_PAGE_FAIL';




export const TERMS_PAGE = 'TERMS_PAGE';
export const TERMS_PAGE_SUCCESS = 'TERMS_PAGE_SUCCESS';
export const TERMS_PAGE_FAIL = 'TERMS_PAGE_FAIL';
