export const LOAD_HOTELS = 'LOAD_HOTELS';
export const LOAD_HOTELS_SUCCESS = 'LOAD_HOTELS_SUCCESS';
export const LOAD_HOTELS_FAIL = 'LOAD_HOTELS_FAIL';


export const LOAD_HOTELS_DETAIL = 'LOAD_HOTELS_DETAIL';
export const LOAD_HOTELS_DETAIL_SUCCESS = 'LOAD_HOTELS_DETAIL_SUCCESS';
export const LOAD_HOTELS_DETAIL_FAIL = 'LOAD_HOTELS_DETAIL_FAIL';



export const SAVE_BOOKING_STATE = 'SAVE_BOOKING_STATE';
export const LOAD_BOOKING_STATE = 'LOAD_BOOKING_STATE';



export const LOAD_DESTINATIONS = 'LOAD_DESTINATIONS';
export const LOAD_DESTINATIONS_SUCCESS = 'LOAD_DESTINATIONS_SUCCESS';
export const LOAD_DESTINATIONS_FAIL = 'LOAD_DESTINATIONS_FAIL';

export const DEST_DETAILS = 'DEST_DETAILS';
export const DEST_DETAILS_SUCCESS = 'DEST_DETAILS_SUCCESS';
export const DEST_DETAILS_FAIL = 'DEST_DETAILS_FAIL';


export const LOAD_TOUR = 'LOAD_TOUR';
export const LOAD_TOUR_SUCCESS = 'LOAD_TOUR_SUCCESS';
export const LOAD_TOUR_FAIL = 'LOAD_TOUR_FAIL';


export const TOUR_DETAILS = 'TOUR_DETAILS';
export const TOUR_DETAILS_SUCCESS = 'TOUR_DETAILS_SUCCESS';
export const TOUR_DETAILS_FAIL = 'TOUR_DETAILS_FAIL';


